server:
  port: 9000
spring:
  application:
    name: spring-microservice-flow
  cloud:
    nacos:
      discovery:
        server-addr: ${CLOUD_SERVER:124.222.147.194:8848}
        namespace: c4cd73ab-aedd-49d9-9835-279a42b7f870